language: csharp
solution: testing.sln
install:
  - nuget restore testing.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release testing.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe .HomeExercises/bin/Debug/ObjectComparison.dll